apiVersion: v1
kind: Namespace
metadata:
  name: burning-candle
---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-node
  namespace: burning-candle
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-node
    spec:
      containers:
        - name: hello-node
          image: christhomas/hello-node:v4
          ports:
            - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: hello-node
  namespace: burning-candle
spec:
  selector:
    app: hello-node
  ports:
    - port: 80
      targetPort: 8080
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-node
  namespace: burning-candle
  annotations:
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/cluster-issuer: "letsencrypt-staging"
spec:
  tls:
    - secretName: hello-node-tls
      hosts:
      - hello-node.burning-candle.com
  rules:
    - host: hello-node.burning-candle.com
      http:
        paths:
          - backend:
              serviceName: hello-node
              servicePort: 80
---

apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: hello-node-tls
  namespace: burning-candle
spec:
  secretName: hello-node-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: hello-node.burning-candle.com
  dnsNames:
    - hello-node.burning-candle.com
  acme:
    config:
    - http01:
        ingress: hello-node
      domains:
        - hello-node.burning-candle.com