# -- Create a pod in the kube-system namespace to run the host path provisioner
apiVersion: v1
kind: Pod
metadata:
  namespace: kube-system
  name: hostpath-provisioner
spec:
  containers:
    - name: hostpath-provisioner
      image: mazdermind/hostpath-provisioner:latest
      imagePullPolicy: "IfNotPresent"
      env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: PV_DIR
          value: /mnt/kubernetes-pv-standard

      volumeMounts:
        - name: pv-volume
          mountPath: /mnt/kubernetes-pv-standard
  volumes:
    - name: pv-volume
      hostPath:
        path: /mnt/kubernetes-pv-standard
---

# -- Create the standard storage class for running on-node hostpath storage
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  namespace: kube-system
  name: standard
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: EnsureExists
provisioner: kubernetes.io/host-path
---

# -- Create a Persistent Volume which claims control over the free space on the app server
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: kube-system
  name: standard
  labels:
    type: standard
spec:
  storageClassName: standard
  capacity:
    storage: 130Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/kubernetes-pv-standard"
