apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-data
  namespace: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 50Gi
  hostPath:
    path: /mnt/kubernetes/gitlab-data
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-postgres
  namespace: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /mnt/kubernetes/gitlab-postgres
---
