baseDomain: antimatter-studios.com

baseIP: 85.93.26.192

gitlabConfigStorageClass: "rook-block"

lego:
  enabled: false

mattermost:
  enabled: false

prometheus:
  enabled: false

gitlab-runner:
  gitlabUrl: http://gitlab.antimatter-studios.com/