version: '2'

services:
  phpfpm:
    image: hello-mysql-phpfpm:v1
    build:
      context: .
      dockerfile: ./docker/Dockerfile.phpfpm
    volumes:
      - ./sock:/sock
      - ./www:/www/

  nginx:
    image: hello-mysql-nginx:v1
    build:
      context: .
      dockerfile: ./docker/Dockerfile.nginx
    ports:
      - 8080:80
    volumes:
      - ./sock:/sock
      - ./www/index.php:/www/index.php