apiVersion: v1
kind: Namespace
metadata:
  name: burning-candle
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-php
  namespace: burning-candle
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-php
    spec:
      containers:
      - name: hello-php-nginx
        image: hello-php-nginx:v2
        ports:
          - containerPort: 8080
        volumeMounts:
        - name: php-socket
          mountPath: /sock
      - name: hello-php-phpfpm
        image: hello-php-phpfpm:v2
        volumeMounts:
          - name: php-socket
            mountPath: /sock
          - name: data
            mountPath: /data
      volumes:
        - name: php-socket
          emptyDir: {}
        - name: data
          persistentVolumeClaim:
            claimName: hello-php

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hello-php
  namespace: burning-candle
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Mi
---

apiVersion: v1
kind: Service
metadata:
  name: hello-php
  namespace: burning-candle
spec:
  selector:
    app: hello-php
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-php
  namespace: burning-candle
  annotations:
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/cluster-issuer: "letsencrypt-staging"
spec:
  tls:
    - secretName: hello-php-burning-candle-com
      hosts:
        - hello-php.burning-candle.com
  rules:
    - host: hello-php.burning-candle.com
      http:
        paths:
          - backend:
              serviceName: hello-php
              servicePort: 80
